require('lspkind').init({
	mode = 'text_symbol',

	-- symbol_map = {
	-- 	Text = "Text",
	-- 	Method = "Method",
	-- 	Function = "Function",
	-- 	Constructor = "Constructor",
	-- 	Field = "Field",
	-- 	Variable = "Variable",
	-- 	Class = "Class",
	-- 	Interface = "Interface",
	-- 	Module = "Module",
	-- 	Property = "Property",
	-- 	Unit = "Unit",
	-- 	Value = "Value",
	-- 	Enum = "Enum",
	-- 	Keyword = "Keyword",
	-- 	Snippet = "Snippet",
	-- 	Color = "Color",
	-- 	File = "File",
	-- 	Reference = "Reference",
	-- 	Folder = "Folder",
	-- 	EnumMember = "EnumMember",
	-- 	Constant = "Constant",
	-- 	Struct = "Struct",
	-- 	Event = "Event",
	-- 	Operator = "Operator",
	-- 	TypeParameter = "TypeParameter"
	-- },

	symbol_map = {
		Text = "",
		Method = "",
		Function = "",
		Constructor = "",
		Field = "",
		Variable = "",
		Class = "",
		Interface = "",
		Module = "",
		Property = "",
		Unit = "",
		Value = "",
		Enum = "",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = ""
	},
})
